const aliases = {
    ///characters
    "Andira": ["monkey"],
    "Anila": ["sheep"],
    "Basara": ["brosara"],
    "Catura": ["cow"],
    "Cidala": ["tiger"],
    "Indala": ["snake"],
    "Khumhira": ["boat", "pig"],
    "Mahira": ["chicken", "rooster"],
    "Makura": ["rabbit", "bunny"],
    "Payila": ["dragon"],
    "Vajra": ["dog"],
    "Vikala": ["rat", "mouse"],
    ///weapons
    "Abu Simbel": ["ra fist"],

    "Gateway-Star Sword": ["celestial sword"],
    "Twinfall-Sky Blade": ["celestial dagger"],
    "Selfless-Rift Spear": ["celestial spear"],
    "Demolition-Tiger Axe": ["celestial axe"],
    "Altruism-Soul Staff": ["celestial staff"],
    "Twinpain-Wolf Gun": ["celestial gun"],
    "Covenant-Ruin Fist": ["celestial fist"],
    "Desolation-Crown Bow": ["celestial bow"],
    "Fantasia-Realm Harp": ["celestial harp"],
    "Oration-Life Katana": ["celestial katana"],

    ///summons
    "Yggdrasil": ["yggy", "yugu"],

    "Beelzebub": ["bubz", "bubs"],
    "Triple Zero": [`"000"`, "t0", "tori"],

    "Michael": ["mika"],

    "Surtr": ["fire crest"],
    "Princess Long Ji": ["water crest", "plj"],
    "Dogu": ["earth crest"],
    "Elil": ["wind crest"],
    "Heimdallr": ["light crest"],
    "Nyarlathotep": ["dark crest"],

    "Gorilla": ["monkey"],

    ///class gear
    "Burlona": ["burlona"],
    "Schalk": ["schalk"],
    "Leviathan Mino": ["levi"],
    "Yggdrasil Mino": ["yggy"],
    "Bahamut Mino": ["baha"],
    "Lu Woh Mino": ["luwoh"],
    "Mini Mimic": ["mimic"],
    "Ouroboros Mino": ["ouro", "cag"],
    "Europa Mino": ["europa"],
    "Wilnas Mino": ["wilnas"],
    "Agastia Simulacrum": ["agastia", "agatura"],
    "Dark Rapture Simulacrum": ["faa", "blue"],
    "Chachazero": ["chachazero", "evangeline"],
    "Perfida": ["ccw"],
    "Qilin Simulacrum": ["qilin"],
    "Coco and Mimi": ["cerberus", "cocomimi"],


    "Round Shield": ["round shield", "round", "hp1"],
    "Buckler": ["buckler", "dodge"],
    "Knight Shield": ["knight shield", "knight", "def1"],
    "Scutum": ["scutum", "def2"],
    "Mythril Shield": ["mythril shield", "mythril", "hp2"],
    "Holy Shield": ["holy shield", "holy", "darkres"],
    "Tiamat Shield": ["tiamat shield", "tiamat", "windatk"],
    "Rose Crystal Shield": ["rose crystal shield", "rose", "superiorelementres"],
    "Spartan Shield": ["spartan shield", "spartan", "default", "def3"],
    "Malice Adarga": ["malice adarga", "malice", "atk"],
    "Archangel's Shield": ["archangel's shield", "angel", "hp3"],
    "Colossus Wall": ["colossus wall", "colossus", "fireatk"],
    "Bahamut Shield": ["bahamut shield", "bahamut", "baha", "cadmg"],
    "Soul of Oneness": ["soul of oneness", "twinelements", "firewaterdef"],
    "Eutr Nogadr Ldeysh": ["eutr nogadr ldeysh", "lindwurm", "debuffres"],
    "Hero's Shield": ["hero's shield", "hero", "gilgamesh", "gilg", "def"],
    "Shield of Lamentation": ["shield of lamentation", "grandorder", "go", "nadmg"],
    "Huanglong Shield": ["huanglong shield", "huanglong", "lightatk"],
    "Qilin Shield": ["qilin shield", "qilin", "darkatk"],
    "Nibelung Mauer": ["nibelung mauer", "alex", "alexiel", "waterres"],
    "Obelisk": ["obelisk", "ennead", "cb"],
    "Shield of the Enthroned": ["atum", "enthroned", "shield of the enthroned"],
    "Lustrous Wall": ["horus", "lustrous wall"],
    "Eth Ldog Ldeysh": ["galleon", "eth ldog ldeysh"],
    "Eth Ckalb Ldeysh": ["fediel", "eth ckalb ldeysh"],
    "Moonhill": ["dias", "diaspora", "moonhill"],
    "Shield of Tenets": ["subhl", "subbie", "tenets", "shield of tenets"],
    "New World Shield": ["world"],
    "Anima Animus Shield": ["anima animus", "aniani"],
    "ESV Shield (Man-Portable)": ["eva"],
};