name: Sync Branches to gh-pages

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  sync-to-gh-pages:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all branches

      # Create a temporary directory to store branch contents
      - name: Create temporary directory
        run: mkdir temp

      # Loop through all branches and copy their contents
      - name: Copy branch contents
        run: |
          for branch in $(git branch -r | grep -v gh-pages | grep -v HEAD | sed 's/origin\///'); do
            git checkout $branch
            if [ "$branch" = "main" ]; then
              cp -r . ../temp/
            else
              mkdir -p ../temp/$branch
              cp -r . ../temp/$branch/
            fi
          done

      # Switch to gh-pages branch
      - name: Switch to gh-pages branch
        run: |
          git checkout gh-pages || git checkout --orphan gh-pages
          rm -rf *
          cp -r ../temp/* .
          rm -rf ../temp

      # Commit and push changes to gh-pages
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Sync branches to gh-pages" || echo "No changes to commit"
          git push origin gh-pages --force